#!/bin/bash -xv

###############################################################################
# The immediately following definitions are constant for a particular version
export PROJECT_NAME=libzmq
export PROJECT_VERSION=master
export JIRA_RELEASE=BUS-1778           # release artifact in jira

# CMakeLists.txt specifies 2.8.12 but version 3 is actually required
export CMAKE_VERSION=3.1.3
